export const CARD = {
    CARD: '[data-cy="serp-tour"]',
    CARD_EUROPE_JEWEL: '[data-id="46922"]',
    CARD_TITLE: 'h4[class="js-ao-serp-tour__name"]',
    CARD_VALUES: 'dl[class="values active"]',
    CARD_PRICE_WRAPPER: 'div[class="br__price-wrapper"]',
    CARD_SAVING: 'div[class="pc saving"]',
    CARD_PRICE_CONTAINER: 'div[class="br__price-wrapper-price-container"]',
    CARD_VIEW_BUTTON: 'div[class="br__button-wrapper"] > a[href="/t/46922"]',
    CARD_DOWNLOAD_BROCHURE: 'div[class="br__button-wrapper"] > button[data-cy="serp-tour--download-brochure"]',
    CARD_DOWNLOAD_BROCHURE_MODAL: 'div[class="js-scout-component__modal-dialog scout-component__modal-dialog"]',
    CARD_DOWNLOAD_BROCHURE_INPUT_EMAIL: '[data-cy="common-download-brochure--email-input"]',
    CARD_DOWNLOAD_BROCHURE_BUTTON: '#pdf_popup > div > div.scout-component__modal-bottom > div > a',
    CARD_DOWNLOAD_BROCHURE_SENT: 'h3[class="scout-component__modal-heading"]',
    CARD_DOWNLOAD_BROCHURE_CLOSE: '#pdf_popup > div > div.scout-component__modal-top > div > button',
    CARD_FAVOURITE: 'li[data-id="46922"] > div[class="bl"] > div[class="sbtn cpr"]',
    CARD_LOGIN_MODAL: 'form[class="overlay"]',
    CARD_LOGIN_EMAIL: '#login_popup > form > input[type=email]:nth-child(5)',
    CARD_LOGIN_PASSWORD: '#login_popup > form > input[type=password]:nth-child(6)',
    CARD_LOGIN_BUTTON: '#login_popup > form > a',
    CARD_ADD_WISHLIST_MODAL: '#wishlist_popup_46922',
    CARD_WISHLIST_CREATE_NEW: '#wishlist_popup_46922 > div.content > div > div.new',
    CARD_WISHLIST_INPUT: '#wishlist_popup_46922 > div.content > div > div.new_form > input',
    CARD_WISHLIST_BUTTON: '#wishlist_popup_46922 > div.content > div > div.new_form > button',
    CARD_WISHLIST_DONE: '#wishlist_popup_46922 > div.content > a'
}    